
title: CSS Advanced
email: Niki70_96@abv.bg
description: Hi, there
baseurl: ""
url: ""
twitter_username: nikinikolov
github_username: nikinikolov

# Build settings
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
